version: "1"
rules:                      # Array of rules
  - base: defualt            # Required. Target branch
    upstream:  lzdnico:defualt    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false    # Optional, merge pull request even when the mergeable_state is not clean. Default: false
